name: Deploy to Lightsail

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

# Allow only one concurrent deployment, but do not cancel in-progress runs.
concurrency:
  group: "deployment"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: install Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Install client dependencies
        run: pnpm install --filter ./client
      - name: Build dist
        run: ./build-dist.sh
      - name: Remote host connection
        env:
            SSH_USER: bitnami
            SSH_KEY: ${{ secrets.MM_LIGHTSAIL_SSH_KEY }}
            SSH_HOST: 34.244.10.237
            SSH_PORT: 22
        run: |
            mkdir -p ~/.ssh/
            echo "$SSH_KEY" > ~/.ssh/remote-webserver.key
            chmod 600 ~/.ssh/remote-webserver.key
            cat >>~/.ssh/config <<END
            Host remote-webserver
              HostName $SSH_HOST
              User $SSH_USER
              Port $SSH_PORT
              IdentityFile ~/.ssh/remote-webserver.key
              StrictHostKeyChecking no
            END
      - name: Install dependencies on runner
        run: sudo apt-get -y update && sudo apt-get --no-install-recommends -y install rsync

      - name: Upload with rsync
        shell: bash
        run: rsync -az --delete --exclude '.git*' --exclude 'data' --exclude 'node_modules' --exclude '.env' --exclude 'public/avatars' ./dist/ remote-webserver:/opt/bitnami/projects/mastermind/

      - name: Install dependencies on server
        run: ssh remote-webserver "export PATH=/opt/bitnami/node/bin:\$PATH && cd /opt/bitnami/projects/mastermind/server && pnpm install --prod"
      - name: Install and restart systemd service
        run: |
            ssh remote-webserver "sudo cp /opt/bitnami/projects/mastermind/server/mastermind.service /etc/systemd/system/ && sudo systemctl daemon-reload && sudo systemctl enable mastermind && sudo systemctl restart mastermind"
